# Generated by Django 3.1.2 on 2020-10-25 23:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='job_type',
            field=models.CharField(choices=[('Full Time', 'Full Time'), ('part Time', 'part Time')], default='', max_length=15),
            preserve_default=False,
        ),
    ]
